/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CourseBAL;
import Model.AssignBean;
import Model.CourseBean;
import Model.TeacherBean;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saad Jatt
 */
public class AssignTeacher extends javax.swing.JInternalFrame {

    /**
     * Creates new form AssignTeacher
     */
    ArrayList <TeacherBean> t_list;
    ArrayList <CourseBean> c_list;
    ArrayList <AssignBean> a_list;
    
    
    DefaultListModel t_model;
    DefaultListModel c_model;
    DefaultTableModel tableModel;
  ArrayList<HashMap<String, Object> >list;
    public AssignTeacher() {
        initComponents();
      //  a_list = new ArrayList<>();
      list= new ArrayList< HashMap<String, Object>>();
        list = Controller.CourseAssignBAL.GetAssignCourse();
        
        t_list = new ArrayList<>();
        t_list = Controller.TeacherBal.getTeacherAssign();
        c_list = new ArrayList<>();
        c_list= Controller.CourseBAL.getCourse();
        
        tableModel = (DefaultTableModel) this.jTable1.getModel();
        
         this.jList_teacher.setModel(new DefaultListModel());
       t_model = (DefaultListModel) this.jList_teacher.getModel();
        
         this.jList_course.setModel(new DefaultListModel());
       c_model = (DefaultListModel) this.jList_course.getModel();
       
       ShowInCourseList();
       ShowInTeacherList();
       showInAssignCourse();
       
      //  System.out.println(t_list);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList_teacher = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_course = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_aasssign = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList_teacher.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/image/LOGIN-logo.jpg")))); // NOI18N
        jScrollPane1.setViewportView(jList_teacher);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 126, 308));

        jList_course.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/image/LOGIN-logo.jpg")))); // NOI18N
        jScrollPane2.setViewportView(jList_course);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 126, 308));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("Teacher and Course List");
        jTable1.setGridColor(new java.awt.Color(0, 153, 255));
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 200, 190));

        jLabel_aasssign.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_aasssign.setToolTipText("Assign Course");
        jLabel_aasssign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_aasssign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_aasssignMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_aasssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, 32));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/as.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_aasssignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_aasssignMouseClicked
        // TODO add your handling code here:
              int t_id = this.jList_teacher.getSelectedIndex();
        int c_id = this.jList_course.getSelectedIndex();
      //  System.out.println("id"+t_id);
        int teacherID= t_list.get(t_id).getId();
        String teacherName= t_list.get(t_id).getName();
        int courseID= c_list.get(c_id).getId();
        System.out.println("treacher_id"+teacherID);
        System.out.println("treacher_Name"+teacherName);
        
       Controller.TeacherBal.assignTeacherID(teacherID);
       
        Controller.CourseAssignBAL.assignTeacherCourse(teacherID, courseID,teacherName);
        
        
        ( (DefaultListModel)this.jList_teacher.getModel()).removeAllElements();
      
        t_list = Controller.TeacherBal.getTeacherAssign();
         for (TeacherBean tb : t_list) {
          this.t_model.addElement(tb); 
    }

     //  ShowInTeacherList();
       showInAssignCourse(); 
    }//GEN-LAST:event_jLabel_aasssignMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_aasssign;
    private javax.swing.JList<String> jList_course;
    private javax.swing.JList<String> jList_teacher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
 public void ShowInTeacherList(){
    
     for (TeacherBean tb : t_list) {
          this.t_model.addElement(tb); 
    }
}
    
        public void ShowInCourseList(){
       
     for (CourseBean cb : c_list) {
     
          this.c_model.addElement(cb); 
      
    }
        }
     public void showInAssignCourse() {
        tableModel.setRowCount(0);
        //System.out.println("---"+StudentBAL1.getStudentSubject());
        for (HashMap<String, Object> map : Controller.CourseAssignBAL.GetAssignCourse()) {
            Vector v = new Vector();
            v.add(map.get("t_name"));
            v.add(map.get("c_name"));
           tableModel.addRow(v);
        }
    }
     
     
}

