/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.CourseBAL.*;
import Model.CourseBean;
import Model.TeacherBean;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saad Jatt
 */
public class CourseCRUD extends javax.swing.JInternalFrame {

    /**
     * Creates new form CourseCRUD
     */
    ArrayList <CourseBean> c_list;
    DefaultTableModel model; 
    public CourseCRUD() {
        initComponents();
        c_list = new ArrayList<>();
        model= (DefaultTableModel) this.jTable1.getModel();
        getCourse();
        showinTable();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_course = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_duration = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_fee = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_save = new javax.swing.JLabel();
        jLabel_save1 = new javax.swing.JLabel();
        jLabel_save2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Couses Settings");
        setToolTipText("Couse Settings");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 110, 93, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        getContentPane().add(jTextField_duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 40, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Duration");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        getContentPane().add(jTextField_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 60, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Monthly Fees");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 102, 255)));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Duration", "Monthly Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("All Courses Here");
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(0, 102, 204));
        jTable1.setSelectionForeground(new java.awt.Color(255, 51, 51));
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 104, 190, 190));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setToolTipText("Back");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 30, 30));

        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 64, 114, -1));

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("per Month");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Months");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 67, -1, -1));

        jLabel_save.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_save.setToolTipText("Save");
        jLabel_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_saveMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 20));

        jLabel_save1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_save1.setToolTipText("Update");
        jLabel_save1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_save1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, 10));

        jLabel_save2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_save2.setToolTipText("Delete");
        jLabel_save2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_save2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_save2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 50, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cs.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents
static  int id = 0;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int id = this.jTable1.getSelectedRow();
        this.jTextField_course.setText(c_list.get(id).getCourse_name());
        this.jTextField_duration.setText(c_list.get(id).getTime());
        this.jTextField_fee.setText(""+c_list.get(id).getFee());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Admin().hide();
        this.dispose();
        new  Admin("saad").setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        // TODO add your handling code here:
        String name = this.jTextField_search.getText();
        SearchTable(name);
        
    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jLabel_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saveMouseClicked
        // TODO add your handling code here:
        if (this.jTextField_course.getText().equals("") || this.jTextField_duration.getText().equals("") || this.jTextField_fee.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please fill the data first then continue");
           
       }
       else{
        String name = this.jTextField_course.getText();
        String time = this.jTextField_duration.getText();
        double fee =Double.parseDouble(""+this.jTextField_fee.getText());
        c_list.add(new CourseBean(id++, name, time, fee));
        addCourse( name, time , fee );
        showinTable();
       }
    }//GEN-LAST:event_jLabel_saveMouseClicked

    private void jLabel_save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_save1MouseClicked
        // TODO add your handling code here:
        if (this.jTextField_course.getText().equals("") || this.jTextField_duration.getText().equals("") || this.jTextField_fee.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please fill the data first then continue");
           
       }
       else{
  
        int id = this.jTable1.getSelectedRow();
        String name = this.jTextField_course.getText();
        String time = this.jTextField_duration.getText();
        double fee =Double.parseDouble(""+this.jTextField_fee.getText());
        updateCourse(c_list.get(id).getId(), name, time, fee);
        showinTable();
        
        }      
    }//GEN-LAST:event_jLabel_save1MouseClicked

    private void jLabel_save2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_save2MouseClicked
        // TODO add your handling code here:
        if (this.jTextField_course.getText().equals("") || this.jTextField_duration.getText().equals("") || this.jTextField_fee.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please fill the data first then continue");
           
       }
       else{
  
        int id = this.jTable1.getSelectedRow();
        cascadeDel(c_list.get(id).getId());
        showinTable();
        }
    }//GEN-LAST:event_jLabel_save2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_save;
    private javax.swing.JLabel jLabel_save1;
    private javax.swing.JLabel jLabel_save2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_course;
    private javax.swing.JTextField jTextField_duration;
    private javax.swing.JTextField jTextField_fee;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
public void showinTable(){
model.setRowCount(0);
c_list= getCourse();
    for (CourseBean cb : c_list) {
        Vector v = new Vector();
        v.add(cb.getCourse_name());
        v.add(cb.getTime());
        v.add(cb.getFee());
        
        model.addRow(v);
    }


}

public void SearchTable(String name){
       model.setRowCount(0);
c_list = Controller.CourseBAL.getSearch(name);
        for (CourseBean cb : c_list) {
        Vector v = new Vector();
        v.add(cb.getCourse_name());
        v.add(cb.getTime());
        v.add(cb.getFee());
        
        model.addRow(v);
    }

}
}
