/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.StudentBean;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saad Jatt
 */
public class FeeSubmit extends javax.swing.JInternalFrame {

    /**
     * Creates new form FeeSubmit
     */
    ArrayList<StudentBean> list;
    DefaultTableModel model;
    
    public FeeSubmit() {
        initComponents();
        list= new ArrayList<>();
        model= (DefaultTableModel) this.jTable1.getModel();
        showInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox_yes = new javax.swing.JCheckBox();
        jCheckBox_no = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student", "Fees", "Paid/Unpaid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 82, 224, 283));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 374, -1, -1));

        jTextField_name.setEnabled(false);
        getContentPane().add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 371, 153, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fee Submit");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jCheckBox_yes.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(jCheckBox_yes);
        jCheckBox_yes.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_yes.setText("Yes");
        getContentPane().add(jCheckBox_yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 409, -1, -1));

        jCheckBox_no.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(jCheckBox_no);
        jCheckBox_no.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_no.setText("No");
        getContentPane().add(jCheckBox_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 409, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setToolTipText("Submitted Fee?");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fee.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int id = this.jTable1.getSelectedRow();
        this.jTextField_name.setText(list.get(id).getName());
        String paid = list.get(id).getPaid();
        if (paid.equals("Paid")){
        this.jCheckBox_yes.setSelected(true);
        
        }
        
       else if (paid.equals("Unpaid")){
        this.jCheckBox_no.setSelected(true);
        
        
       }
        
     
        
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int id = this.jTable1.getSelectedRow();
        
          Controller.StudentBAL.feeSubmit(list.get(id).getStudentId());
          showInTable();
        // System.err.println(list.get(id).getStudentId());
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox_no;
    private javax.swing.JCheckBox jCheckBox_yes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
public void showInTable(){
    model.setRowCount(0);
  //  System.out.println(TeacherForm.teacher_id);
list = Controller.StudentBAL.getStudentFee();
    for (StudentBean sb : list) {
        
        Vector v = new Vector();
        v.add(sb.getName());
        v.add(sb.getFees());
        v.add(sb.getPaid());
        model.addRow(v);
    }


}

}
