/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginBAL;
import Model.TeacherBean;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class TeacherCRUD extends javax.swing.JInternalFrame {

    
    ArrayList<TeacherBean> t1_list;
    DefaultTableModel model;
    public TeacherCRUD() {
        initComponents();
        t1_list = new ArrayList<>();
        model = (DefaultTableModel) this.jTable_teachers.getModel();
        t1_list = Controller.TeacherBal.getTeacher();
        showinTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_teachers = new javax.swing.JTable();
        jTextField_age = new javax.swing.JTextField();
        jTextField_search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("TeacherCRUD");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gender");

        jRadioButton_male.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton_male.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_male.setText("Male");

        jRadioButton_female.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton_female.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_female.setText("Female");

        jTable_teachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Age", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_teachers.setGridColor(new java.awt.Color(0, 102, 204));
        jTable_teachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_teachersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_teachers);

        jTextField_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchActionPerformed(evt);
            }
        });
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Set Password");

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search");

        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tea.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jRadioButton_male)
                        .addGap(3, 3, 3)
                        .addComponent(jRadioButton_female))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton_male)
                    .addComponent(jRadioButton_female))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Admin().hide();
        this.dispose();
        new  Admin("saad").setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTable_teachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_teachersMouseClicked
        // TODO add your handling code here:
        
        
        int id = this.jTable_teachers.getSelectedRow();
        this.jTextField_name.setText(t1_list.get(id).getName());
        this.jTextField_age.setText(""+t1_list.get(id).getAge());
       String gender = t1_list.get(id).getGender();
       if (gender.equals("Male")){
       this.jRadioButton_male.setSelected(true);
       }
      else if (gender.equals("Female")){
       this.jRadioButton_female.setSelected(true);
       }
        this.jPasswordField1.setText(t1_list.get(id).getPassword());
    }//GEN-LAST:event_jTable_teachersMouseClicked

    private void jTextField_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyPressed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jTextField_searchKeyPressed

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        // TODO add your handling code here:
                String name = this.jTextField_search.getText();
        SearchTable(name);
  
    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jTextField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
          int id =1;
       String name = this.jTextField_name.getText();
       String gender = "";
       int age = Integer.parseInt(this.jTextField_age.getText());
      
       if (this.jRadioButton_male.isSelected()){
           
           gender = "Male";
       }
      else if (this.jRadioButton_female.isSelected()){
           
           //this.jRadioButton_female.setSelected(true);
           gender = "Female";
       }
       
       String password = this.jPasswordField1.getText();
       
       Controller.LoginBAL.addTeacherLogin(name, password);
       Controller.TeacherBal.addTeacher(name, gender, age, password);
       showinTable();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        if(this.jTextField_name.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Please Select Row first ");
        
        }
        else{
               int id = this.jTable_teachers.getSelectedRow(); 
        String name = this.jTextField_name.getText();
       int age=Integer.parseInt(this.jTextField_age.getText());
       String password=this.jPasswordField1.getText();
       
        String gender= "";
        if (this.jRadioButton_male.isSelected()) {
            gender="Male";

        } else {
            gender="Female";

        }
//        model.setValueAt(this.jTextField_name.getText(), id,0 );
//       
//        model.setValueAt(gender, id, 1);
//         model.setValueAt(this.jTextField_age.getText(), id, 2);
//        model.setValueAt(this.jPasswordField1.getText(), id, 3);
//       

       
        int i = Controller.TeacherBal.updateTeacher(t1_list.get(id).getId(), name, gender, age, password);
        int j=LoginBAL.updateLogin(t1_list.get(id).getId(), name, password);
       
        showinTable();
        }
        this.jTextField_name.setText("");
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         int id = this.jTable_teachers.getSelectedRow();
        
        int i = Controller.TeacherBal.cascadeDel(t1_list.get(id).getId());
        System.out.println(t1_list.get(id).getId());
        
        int j = Controller.LoginBAL.LoginDel(t1_list.get(id).getId());
        showinTable();
    }//GEN-LAST:event_jLabel11MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_teachers;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
//public void progress(){
//      
//        new Thread() {
//            public void run() {
//                 for(int i =0; i < 100; i++){
//     jProgressBar1.setValue(i);
//     
//        try {
//            Thread.sleep(100);
//        } catch (InterruptedException e1) {
//            e1.printStackTrace();
//        }
//        //System.out.println(i);
//     
//    }
//                
//            }
//            
//        }.start();
//
//}
public void showinTable (){
model.setRowCount(0);
t1_list = Controller.TeacherBal.getTeacher();

    for (TeacherBean tb : t1_list) {
        Vector v = new Vector();
        v.add(tb.getName());
        v.add(tb.getGender());
        v.add(tb.getAge());
        v.add(tb.getPassword());
       
        model.addRow(v);
        
    }

}

public void SearchTable(String name){
       model.setRowCount(0);
t1_list = Controller.TeacherBal.getSearch(name);
    for (TeacherBean tb : t1_list) {
        Vector v = new Vector();
         v.add(tb.getName());
        v.add(tb.getGender());
        v.add(tb.getAge());
        v.add(tb.getPassword());
       
        model.addRow(v);
        
    }

}


}
